package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Band;
import org.mybatis.cdi.Mapper;

@Mapper
public interface BandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAND
     *
     * @mbg.generated Mon May 15 23:12:50 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAND
     *
     * @mbg.generated Mon May 15 23:12:50 EEST 2023
     */
    int insert(Band record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAND
     *
     * @mbg.generated Mon May 15 23:12:50 EEST 2023
     */
    Band selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAND
     *
     * @mbg.generated Mon May 15 23:12:50 EEST 2023
     */
    List<Band> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BAND
     *
     * @mbg.generated Mon May 15 23:12:50 EEST 2023
     */
    int updateByPrimaryKey(Band record);
}