package lt.vu.mybatis.model;

public class Musician {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MUSICIAN.ID
     *
     * @mbg.generated Mon May 15 23:12:50 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MUSICIAN.INSTRUMENT
     *
     * @mbg.generated Mon May 15 23:12:50 EEST 2023
     */
    private String instrument;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MUSICIAN.NAME
     *
     * @mbg.generated Mon May 15 23:12:50 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MUSICIAN.BAND_ID
     *
     * @mbg.generated Mon May 15 23:12:50 EEST 2023
     */
    private Integer bandId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MUSICIAN.ID
     *
     * @return the value of PUBLIC.MUSICIAN.ID
     *
     * @mbg.generated Mon May 15 23:12:50 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MUSICIAN.ID
     *
     * @param id the value for PUBLIC.MUSICIAN.ID
     *
     * @mbg.generated Mon May 15 23:12:50 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MUSICIAN.INSTRUMENT
     *
     * @return the value of PUBLIC.MUSICIAN.INSTRUMENT
     *
     * @mbg.generated Mon May 15 23:12:50 EEST 2023
     */
    public String getInstrument() {
        return instrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MUSICIAN.INSTRUMENT
     *
     * @param instrument the value for PUBLIC.MUSICIAN.INSTRUMENT
     *
     * @mbg.generated Mon May 15 23:12:50 EEST 2023
     */
    public void setInstrument(String instrument) {
        this.instrument = instrument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MUSICIAN.NAME
     *
     * @return the value of PUBLIC.MUSICIAN.NAME
     *
     * @mbg.generated Mon May 15 23:12:50 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MUSICIAN.NAME
     *
     * @param name the value for PUBLIC.MUSICIAN.NAME
     *
     * @mbg.generated Mon May 15 23:12:50 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MUSICIAN.BAND_ID
     *
     * @return the value of PUBLIC.MUSICIAN.BAND_ID
     *
     * @mbg.generated Mon May 15 23:12:50 EEST 2023
     */
    public Integer getBandId() {
        return bandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MUSICIAN.BAND_ID
     *
     * @param bandId the value for PUBLIC.MUSICIAN.BAND_ID
     *
     * @mbg.generated Mon May 15 23:12:50 EEST 2023
     */
    public void setBandId(Integer bandId) {
        this.bandId = bandId;
    }
}